name = "uncover"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "uncover-db"
database_id = "e57bc084-f5c2-4ada-86c8-d1eb3ea6fd90"
migrations_dir = "migrations"
